spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

# spring.datasource.url=jdbc:mysql://localhost:3306/empjay
# spring.datasource.username=root
# spring.datasource.password=

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# spring.jpa.properties.hibernate.format_sql=true

# # JWT Configuration
app.jwt-secret=MyVerySecretKeyForFAANGEmployeeManagementSystem2024WhichIsLongEnough
app.jwt-expiration-milliseconds=604800000
